// Code generated by protoc-gen-go. DO NOT EDIT.
// source: dke/v1/dke.proto

package dke

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	_ "github.com/grpc-ecosystem/grpc-gateway/protoc-gen-swagger/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Gets the public key
type PublicKeyRequest struct {
	// Required. Key Name
	// e.g. `TestKey1`.
	KeyName              string   `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyRequest) Reset()         { *m = PublicKeyRequest{} }
func (m *PublicKeyRequest) String() string { return proto.CompactTextString(m) }
func (*PublicKeyRequest) ProtoMessage()    {}
func (*PublicKeyRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0079cc955f315a, []int{0}
}

func (m *PublicKeyRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyRequest.Unmarshal(m, b)
}
func (m *PublicKeyRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyRequest.Marshal(b, m, deterministic)
}
func (m *PublicKeyRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyRequest.Merge(m, src)
}
func (m *PublicKeyRequest) XXX_Size() int {
	return xxx_messageInfo_PublicKeyRequest.Size(m)
}
func (m *PublicKeyRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyRequest proto.InternalMessageInfo

func (m *PublicKeyRequest) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

// Response message for [AzureDKEKeyManagementService.GetPublicKey][].
type PublicKeyResponse struct {
	// The key
	Key                  *PublicKeyResponse_Key `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{}               `json:"-"`
	XXX_unrecognized     []byte                 `json:"-"`
	XXX_sizecache        int32                  `json:"-"`
}

func (m *PublicKeyResponse) Reset()         { *m = PublicKeyResponse{} }
func (m *PublicKeyResponse) String() string { return proto.CompactTextString(m) }
func (*PublicKeyResponse) ProtoMessage()    {}
func (*PublicKeyResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0079cc955f315a, []int{1}
}

func (m *PublicKeyResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyResponse.Unmarshal(m, b)
}
func (m *PublicKeyResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyResponse.Marshal(b, m, deterministic)
}
func (m *PublicKeyResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyResponse.Merge(m, src)
}
func (m *PublicKeyResponse) XXX_Size() int {
	return xxx_messageInfo_PublicKeyResponse.Size(m)
}
func (m *PublicKeyResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyResponse proto.InternalMessageInfo

func (m *PublicKeyResponse) GetKey() *PublicKeyResponse_Key {
	if m != nil {
		return m.Key
	}
	return nil
}

// Key information
type PublicKeyResponse_Key struct {
	// Key type
	Kty string `protobuf:"bytes,1,opt,name=kty,proto3" json:"kty,omitempty"`
	// Key
	N string `protobuf:"bytes,2,opt,name=n,proto3" json:"n,omitempty"`
	// Key exponent (typically 65537)
	E int32 `protobuf:"varint,3,opt,name=e,proto3" json:"e,omitempty"`
	// Algorithm
	Alg string `protobuf:"bytes,4,opt,name=alg,proto3" json:"alg,omitempty"`
	// Key ID
	Kid                  string   `protobuf:"bytes,5,opt,name=kid,proto3" json:"kid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PublicKeyResponse_Key) Reset()         { *m = PublicKeyResponse_Key{} }
func (m *PublicKeyResponse_Key) String() string { return proto.CompactTextString(m) }
func (*PublicKeyResponse_Key) ProtoMessage()    {}
func (*PublicKeyResponse_Key) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0079cc955f315a, []int{1, 0}
}

func (m *PublicKeyResponse_Key) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PublicKeyResponse_Key.Unmarshal(m, b)
}
func (m *PublicKeyResponse_Key) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PublicKeyResponse_Key.Marshal(b, m, deterministic)
}
func (m *PublicKeyResponse_Key) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PublicKeyResponse_Key.Merge(m, src)
}
func (m *PublicKeyResponse_Key) XXX_Size() int {
	return xxx_messageInfo_PublicKeyResponse_Key.Size(m)
}
func (m *PublicKeyResponse_Key) XXX_DiscardUnknown() {
	xxx_messageInfo_PublicKeyResponse_Key.DiscardUnknown(m)
}

var xxx_messageInfo_PublicKeyResponse_Key proto.InternalMessageInfo

func (m *PublicKeyResponse_Key) GetKty() string {
	if m != nil {
		return m.Kty
	}
	return ""
}

func (m *PublicKeyResponse_Key) GetN() string {
	if m != nil {
		return m.N
	}
	return ""
}

func (m *PublicKeyResponse_Key) GetE() int32 {
	if m != nil {
		return m.E
	}
	return 0
}

func (m *PublicKeyResponse_Key) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *PublicKeyResponse_Key) GetKid() string {
	if m != nil {
		return m.Kid
	}
	return ""
}

// Decrypt using the private key. The encrypted text must have been encrypted
// using the private key.
type DecryptRequest struct {
	// Required. Name of the key
	// e.g. `TestKey1`.
	KeyName string `protobuf:"bytes,1,opt,name=key_name,json=keyName,proto3" json:"key_name,omitempty"`
	// Required. The identifier of the key
	// (as provided by [AzureDKEKeyManagementService.GetKey][])
	// e.g.
	// `D798B899-3350-4F5C-A608-2EDA37CB0EBD`
	KeyId string `protobuf:"bytes,2,opt,name=key_id,json=keyId,proto3" json:"key_id,omitempty"`
	// Required. Algorithm
	// e.g. `RSA-OAEP-256`
	Alg string `protobuf:"bytes,3,opt,name=alg,proto3" json:"alg,omitempty"`
	// Required. Encrypted value, base64 encoded
	Value                string   `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptRequest) Reset()         { *m = DecryptRequest{} }
func (m *DecryptRequest) String() string { return proto.CompactTextString(m) }
func (*DecryptRequest) ProtoMessage()    {}
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0079cc955f315a, []int{2}
}

func (m *DecryptRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptRequest.Unmarshal(m, b)
}
func (m *DecryptRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptRequest.Marshal(b, m, deterministic)
}
func (m *DecryptRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptRequest.Merge(m, src)
}
func (m *DecryptRequest) XXX_Size() int {
	return xxx_messageInfo_DecryptRequest.Size(m)
}
func (m *DecryptRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptRequest proto.InternalMessageInfo

func (m *DecryptRequest) GetKeyName() string {
	if m != nil {
		return m.KeyName
	}
	return ""
}

func (m *DecryptRequest) GetKeyId() string {
	if m != nil {
		return m.KeyId
	}
	return ""
}

func (m *DecryptRequest) GetAlg() string {
	if m != nil {
		return m.Alg
	}
	return ""
}

func (m *DecryptRequest) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

// Response message for [AzureDKEKeyManagementService.Decrypt][].
type DecryptResponse struct {
	// The decrypted data, base64 encoded
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DecryptResponse) Reset()         { *m = DecryptResponse{} }
func (m *DecryptResponse) String() string { return proto.CompactTextString(m) }
func (*DecryptResponse) ProtoMessage()    {}
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_df0079cc955f315a, []int{3}
}

func (m *DecryptResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DecryptResponse.Unmarshal(m, b)
}
func (m *DecryptResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DecryptResponse.Marshal(b, m, deterministic)
}
func (m *DecryptResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DecryptResponse.Merge(m, src)
}
func (m *DecryptResponse) XXX_Size() int {
	return xxx_messageInfo_DecryptResponse.Size(m)
}
func (m *DecryptResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DecryptResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DecryptResponse proto.InternalMessageInfo

func (m *DecryptResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

func init() {
	proto.RegisterType((*PublicKeyRequest)(nil), "azure.dke.v1.PublicKeyRequest")
	proto.RegisterType((*PublicKeyResponse)(nil), "azure.dke.v1.PublicKeyResponse")
	proto.RegisterType((*PublicKeyResponse_Key)(nil), "azure.dke.v1.PublicKeyResponse.Key")
	proto.RegisterType((*DecryptRequest)(nil), "azure.dke.v1.DecryptRequest")
	proto.RegisterType((*DecryptResponse)(nil), "azure.dke.v1.DecryptResponse")
}

func init() { proto.RegisterFile("dke/v1/dke.proto", fileDescriptor_df0079cc955f315a) }

var fileDescriptor_df0079cc955f315a = []byte{
	// 665 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x4f, 0x6f, 0xd3, 0x30,
	0x14, 0xc7, 0x0d, 0xdd, 0x86, 0xd7, 0xfd, 0x33, 0x9b, 0x28, 0x51, 0x61, 0xa1, 0x1c, 0x98, 0xa6,
	0x35, 0x59, 0x3b, 0xb8, 0x8c, 0x53, 0xc7, 0x26, 0x58, 0x0b, 0x53, 0x35, 0x40, 0x48, 0xe3, 0x80,
	0xdc, 0xf8, 0x29, 0x35, 0x49, 0xec, 0x90, 0xa4, 0x9d, 0xb2, 0x69, 0x17, 0xa4, 0x49, 0x48, 0xdc,
	0xc6, 0x89, 0x33, 0x27, 0xbe, 0x0c, 0x17, 0xbe, 0x02, 0xdf, 0x81, 0x2b, 0x72, 0x92, 0x96, 0x4e,
	0xd3, 0x98, 0x38, 0xc5, 0xf6, 0xfb, 0xbd, 0xfc, 0xfe, 0x58, 0x7e, 0x78, 0x9e, 0xb9, 0x60, 0x0d,
	0xea, 0x16, 0x73, 0xc1, 0x0c, 0x42, 0x19, 0x4b, 0x52, 0xa2, 0x47, 0xfd, 0x10, 0x4c, 0x75, 0x30,
	0xa8, 0xeb, 0x15, 0x47, 0x4a, 0xc7, 0x03, 0x8b, 0x06, 0xdc, 0xa2, 0x42, 0xc8, 0x98, 0xc6, 0x5c,
	0x8a, 0x28, 0xc3, 0xea, 0x4b, 0x63, 0xd5, 0x5e, 0x1c, 0x07, 0xf9, 0xf1, 0x5a, 0xfa, 0xb1, 0x6b,
	0x0e, 0x88, 0x5a, 0x74, 0x48, 0x1d, 0x07, 0x42, 0x4b, 0x06, 0x69, 0xe3, 0xc5, 0x9f, 0x54, 0x6b,
	0x78, 0xbe, 0xd3, 0xef, 0x7a, 0xdc, 0x6e, 0x43, 0xb2, 0x0f, 0x1f, 0xfa, 0x10, 0xc5, 0xe4, 0x36,
	0x9e, 0x72, 0x21, 0x79, 0x27, 0xa8, 0x0f, 0x65, 0x64, 0xa0, 0x95, 0x1b, 0xfb, 0x93, 0x2e, 0x24,
	0x7b, 0xd4, 0x87, 0xea, 0x37, 0x84, 0x17, 0xc6, 0xf0, 0x51, 0x20, 0x45, 0x04, 0xe4, 0x11, 0xd6,
	0x5c, 0x48, 0x52, 0xec, 0x74, 0xe3, 0xbe, 0x39, 0xee, 0xc1, 0xbc, 0x80, 0x36, 0xd5, 0x5a, 0xe1,
	0xf5, 0x37, 0x58, 0x6b, 0x43, 0x42, 0xe6, 0xb1, 0xe6, 0xc6, 0x49, 0xce, 0xa4, 0x96, 0xa4, 0x84,
	0x91, 0x28, 0x17, 0xd2, 0x3d, 0x12, 0x6a, 0x07, 0x65, 0xcd, 0x40, 0x2b, 0xc5, 0x7d, 0x04, 0x0a,
	0x4d, 0x3d, 0xa7, 0x7c, 0x3d, 0x43, 0x53, 0xcf, 0x49, 0xfb, 0x39, 0x2b, 0x17, 0xf3, 0x7e, 0xce,
	0xaa, 0xef, 0xf1, 0xec, 0x36, 0xd8, 0x61, 0x12, 0xc4, 0x57, 0x5b, 0x22, 0x4b, 0x78, 0x42, 0x95,
	0x38, 0xcb, 0x19, 0x8b, 0x2e, 0x24, 0xbb, 0x6c, 0xc8, 0xa3, 0xfd, 0xe5, 0x59, 0xc4, 0xc5, 0x01,
	0xf5, 0xfa, 0x90, 0x73, 0x67, 0x9b, 0xea, 0x03, 0x3c, 0x37, 0xe2, 0xca, 0xe3, 0x18, 0x01, 0x15,
	0x53, 0x29, 0x07, 0x36, 0x3e, 0x6b, 0xb8, 0xd2, 0x54, 0xc9, 0x6c, 0xb7, 0x77, 0xda, 0x90, 0xbc,
	0xa0, 0x82, 0x3a, 0xe0, 0x83, 0x88, 0x5f, 0x42, 0x38, 0xe0, 0x36, 0x90, 0xaf, 0x08, 0x97, 0x9e,
	0x42, 0x3c, 0x0a, 0x8c, 0xdc, 0xbd, 0x34, 0xc9, 0xd4, 0x94, 0xbe, 0x7c, 0x45, 0xd2, 0xd5, 0x67,
	0x67, 0xcd, 0x46, 0x6b, 0x11, 0x6b, 0x0f, 0xd7, 0xd7, 0xc9, 0x0c, 0x9e, 0xde, 0x15, 0x03, 0xea,
	0x71, 0x66, 0xb8, 0x90, 0xb4, 0x74, 0x75, 0xba, 0x41, 0x6e, 0xe2, 0x85, 0x0e, 0x84, 0x3e, 0x8f,
	0x22, 0x2e, 0x85, 0xc1, 0x40, 0x70, 0x60, 0x1f, 0x7f, 0xfe, 0xfa, 0x52, 0x98, 0x21, 0xd3, 0xd6,
	0xf1, 0x30, 0xb2, 0x13, 0xf2, 0x03, 0xe1, 0xc9, 0xdc, 0x26, 0xa9, 0x9c, 0xa7, 0x3d, 0x9f, 0xb4,
	0x7e, 0xe7, 0x92, 0x6a, 0x2e, 0xe9, 0x14, 0x9d, 0x35, 0xdf, 0xb6, 0xca, 0x99, 0xa6, 0x05, 0x3c,
	0x37, 0xd4, 0x14, 0x66, 0xed, 0xad, 0x25, 0x55, 0xa9, 0x93, 0x59, 0x5c, 0x7a, 0x2d, 0x68, 0x3f,
	0xee, 0xc9, 0x90, 0x1f, 0x01, 0xfb, 0x97, 0xdc, 0x6e, 0x09, 0x63, 0x3c, 0xb1, 0x05, 0x34, 0x84,
	0x90, 0x5c, 0x4b, 0xc5, 0xdf, 0xab, 0x56, 0xc6, 0xc4, 0x67, 0x4b, 0xce, 0x4e, 0x2c, 0x96, 0x89,
	0xd9, 0x44, 0xab, 0x5b, 0xdf, 0x0b, 0x67, 0xcd, 0xdf, 0x88, 0xec, 0xe1, 0x72, 0x7a, 0x27, 0xc6,
	0xe8, 0x46, 0x42, 0x63, 0xbb, 0xbd, 0x63, 0x34, 0x3b, 0xbb, 0xd5, 0x1a, 0xc6, 0xaf, 0x7a, 0xd4,
	0x83, 0xc8, 0x78, 0xd2, 0x79, 0x4e, 0x96, 0xd5, 0x13, 0x8b, 0x36, 0xad, 0xf4, 0xb1, 0xe6, 0x16,
	0x03, 0x29, 0x18, 0xf8, 0x54, 0x30, 0x93, 0xcb, 0x86, 0x56, 0x37, 0xd7, 0xf5, 0x5b, 0x97, 0x54,
	0x57, 0x51, 0xe1, 0xe0, 0x13, 0xc2, 0xa7, 0x68, 0xa4, 0xf4, 0x78, 0x4a, 0xd3, 0x67, 0x9a, 0xb9,
	0xc3, 0xf4, 0x49, 0x1a, 0x85, 0x15, 0xad, 0x51, 0x1f, 0xd2, 0x78, 0xd2, 0xe1, 0xc2, 0x3c, 0xe4,
	0x82, 0xc9, 0xc3, 0xc8, 0x14, 0x10, 0x5b, 0xb6, 0xf4, 0x7d, 0x29, 0x2c, 0xa9, 0x62, 0x69, 0x58,
	0xa3, 0x70, 0x36, 0xff, 0xbf, 0xe5, 0x60, 0xcd, 0xe1, 0x71, 0xaf, 0xdf, 0x35, 0x6d, 0xe9, 0x5b,
	0x71, 0x8f, 0x7a, 0x91, 0x1d, 0x78, 0x35, 0x2e, 0x2d, 0x3f, 0xaa, 0x31, 0x17, 0x6a, 0x6a, 0xa2,
	0x64, 0xa3, 0xe9, 0x31, 0x73, 0xa1, 0x3b, 0x91, 0x8e, 0x8a, 0x8d, 0x3f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x0c, 0x10, 0x5c, 0x7e, 0xaf, 0x04, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AzureDKEKeyManagementServiceClient is the client API for AzureDKEKeyManagementService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AzureDKEKeyManagementServiceClient interface {
	// Gets the public key
	GetPublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error)
	// Decrypts using the private key. Credentials need to be provided via the
	// Authorization header with the Bearer JWT token.
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
}

type azureDKEKeyManagementServiceClient struct {
	cc *grpc.ClientConn
}

func NewAzureDKEKeyManagementServiceClient(cc *grpc.ClientConn) AzureDKEKeyManagementServiceClient {
	return &azureDKEKeyManagementServiceClient{cc}
}

func (c *azureDKEKeyManagementServiceClient) GetPublicKey(ctx context.Context, in *PublicKeyRequest, opts ...grpc.CallOption) (*PublicKeyResponse, error) {
	out := new(PublicKeyResponse)
	err := c.cc.Invoke(ctx, "/azure.dke.v1.AzureDKEKeyManagementService/GetPublicKey", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *azureDKEKeyManagementServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, "/azure.dke.v1.AzureDKEKeyManagementService/Decrypt", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AzureDKEKeyManagementServiceServer is the server API for AzureDKEKeyManagementService service.
type AzureDKEKeyManagementServiceServer interface {
	// Gets the public key
	GetPublicKey(context.Context, *PublicKeyRequest) (*PublicKeyResponse, error)
	// Decrypts using the private key. Credentials need to be provided via the
	// Authorization header with the Bearer JWT token.
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
}

func RegisterAzureDKEKeyManagementServiceServer(s *grpc.Server, srv AzureDKEKeyManagementServiceServer) {
	s.RegisterService(&_AzureDKEKeyManagementService_serviceDesc, srv)
}

func _AzureDKEKeyManagementService_GetPublicKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublicKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AzureDKEKeyManagementServiceServer).GetPublicKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.dke.v1.AzureDKEKeyManagementService/GetPublicKey",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AzureDKEKeyManagementServiceServer).GetPublicKey(ctx, req.(*PublicKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AzureDKEKeyManagementService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AzureDKEKeyManagementServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/azure.dke.v1.AzureDKEKeyManagementService/Decrypt",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AzureDKEKeyManagementServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AzureDKEKeyManagementService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "azure.dke.v1.AzureDKEKeyManagementService",
	HandlerType: (*AzureDKEKeyManagementServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPublicKey",
			Handler:    _AzureDKEKeyManagementService_GetPublicKey_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _AzureDKEKeyManagementService_Decrypt_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "dke/v1/dke.proto",
}
